name: macos

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Brew-Nats
      run: brew install nats-server -DVV 

